// =============================================================================
//  build-epik.cjs
//  Copyright © 2026 TieredUp Tech, Inc.
//
//  Generates the static-hosting artifacts the Epik/Apache stack needs, INTO dist/,
//  so they survive `vite build` emptying dist/. Run after prerender.cjs.
//
//  Emits into dist/:
//    - resolver-config.php  : PRODUCT_RE copied verbatim out of server.cjs
//                             (single source of truth for the product boundary)
//    - redirects.php        : the 301 map, from product-redirects.json
//    - gone.html            : the 410 shell, transformed from index.html exactly
//                             the way server.cjs builds GONE_SHELL at boot
//    - .htaccess            : copied from deploy/.htaccess
//    - resolver.php         : copied from deploy/resolver.php
// =============================================================================

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');
const DEPLOY = path.join(ROOT, 'deploy');

// Staging builds get a Basic-Auth + noindex guard appended to .htaccess. It is
// NEVER part of a production artifact — see the STAGING branch vs the production
// self-check at the end of this script. The sentinel is what the production
// deploy greps for to refuse shipping a contaminated .htaccess.
const STAGING = process.argv.includes('--staging');
const GUARD_SENTINEL = 'PRB-STAGING-GUARD';

if (!fs.existsSync(DIST)) {
  console.error(`  ✗ dist/ not found at ${DIST} — run the vite build + prerender first`);
  process.exit(1);
}

// ── 1. Extract PRODUCT_RE from server.cjs (copy, never retype) ───────────────
const serverSrc = fs.readFileSync(path.join(ROOT, 'server.cjs'), 'utf8');
const m = serverSrc.match(/const PRODUCT_RE = \/(.+)\/;\s*$/m);
if (!m) {
  console.error('  ✗ could not locate `const PRODUCT_RE = /.../;` in server.cjs');
  process.exit(1);
}
const productPattern = m[1]; // e.g. ^\/parts\/[^/]+\/[^/]+-\d+\/?$
if (productPattern.includes('#') || productPattern.includes("'")) {
  // Our PHP wrapper uses `#` as the delimiter inside a single-quoted string.
  console.error('  ✗ PRODUCT_RE contains a `#` or a single quote — adjust the PHP delimiter/escaping');
  process.exit(1);
}
const resolverConfig =
  '<?php\n' +
  '// GENERATED by build-epik.cjs — DO NOT EDIT.\n' +
  '// PRODUCT_RE copied verbatim from server.cjs so the product/non-product boundary\n' +
  '// is byte-identical to the Node stack. `#` delimiter avoids escaping the slashes.\n' +
  "define('RESOLVER_PRODUCT_RE', '#" + productPattern + "#');\n";
fs.writeFileSync(path.join(DIST, 'resolver-config.php'), resolverConfig, 'utf8');

// ── 2. redirects.php from product-redirects.json (drop "//" comment keys) ────
let rawMap = {};
try {
  rawMap = JSON.parse(fs.readFileSync(path.join(ROOT, 'product-redirects.json'), 'utf8'));
} catch (e) {
  console.warn(`  ⚠ product-redirects.json not read (${e.message}) — emitting empty map (all 410)`);
}
const phpStr = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
let redirectCount = 0;
let redirectsPhp = '<?php\n// GENERATED by build-epik.cjs from product-redirects.json — DO NOT EDIT.\nreturn array(\n';
for (const [k, v] of Object.entries(rawMap)) {
  if (k.startsWith('//')) continue; // JSON comment convention
  redirectsPhp += '  ' + phpStr(k) + ' => ' + phpStr(v) + ',\n';
  redirectCount++;
}
redirectsPhp += ');\n';
fs.writeFileSync(path.join(DIST, 'redirects.php'), redirectsPhp, 'utf8');

// ── 3. gone.html — same transform server.cjs applies to build GONE_SHELL ─────
let goneHtml;
try {
  goneHtml = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8')
    .replace(/\s*<meta name="(?:robots|googlebot|bingbot)"[^>]*>/gi, '')
    .replace(/\s*<link[^>]*rel="canonical"[^>]*>/gi, '')
    .replace(/<head>/i, '<head>\n    <meta name="robots" content="noindex">');
} catch (e) {
  goneHtml = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
    + '<meta name="robots" content="noindex">'
    + '<title>Product Not Found — Pro Rig Builder</title></head>'
    + '<body><h1>Product Not Found</h1></body></html>';
}
// Guard: a 410 shell must never advertise itself as indexable.
if (/content="index/i.test(goneHtml) || !/content="noindex"/i.test(goneHtml)) {
  console.error('  ✗ gone.html failed the noindex invariant — index directive present or noindex missing');
  process.exit(1);
}
fs.writeFileSync(path.join(DIST, 'gone.html'), goneHtml, 'utf8');

// ── 4. Copy the static config into dist/ (edit these in deploy/, never in dist/)
fs.copyFileSync(path.join(DEPLOY, '.htaccess'), path.join(DIST, '.htaccess'));
fs.copyFileSync(path.join(DEPLOY, 'resolver.php'), path.join(DIST, 'resolver.php'));
// _env.php reports the R1 invariant + opcache state per worker. It ships in
// every artifact (both stacks) so the pull healthcheck and the watchdog can
// assert on it — see DESIGN-pull-deploy.md §3.3 / §6.9.
fs.copyFileSync(path.join(DEPLOY, '_env.php'), path.join(DIST, '_env.php'));

// ── 5. Staging guard (Basic Auth primary, noindex secondary) OR production
//      self-check that no guard is present. Basic Auth is deliberately the
//      primary layer: if it ever leaks to prod the site 401s and is noticed in
//      minutes, whereas a stray noindex de-indexes silently (the 2026-07-27
//      incident). The guard is generated ONLY here, only under --staging.
const htaccessPath = path.join(DIST, '.htaccess');
const htpasswdPath = path.join(DIST, '.htpasswd');
let guardNote = '';
if (STAGING) {
  const authRaw = process.env.EPIK_STAGING_BASIC_AUTH || '';
  if (!authRaw.includes(':')) {
    console.error('  ✗ --staging requires EPIK_STAGING_BASIC_AUTH="user:password"');
    process.exit(2);
  }
  const stagingRoot = (process.env.EPIK_REMOTE_ROOT || '').replace(/\/+$/, '');
  if (!stagingRoot) {
    console.error('  ✗ --staging requires EPIK_REMOTE_ROOT (the staging docroot) for the AuthUserFile path');
    process.exit(2);
  }
  const ci = authRaw.indexOf(':');
  const user = authRaw.slice(0, ci);
  const pass = authRaw.slice(ci + 1);
  // {SHA} htpasswd entry — no external deps, supported by Apache 2.4. Fine for a
  // single shared staging gate behind HTTPS (not real user credentials).
  const entry = `${user}:{SHA}${crypto.createHash('sha1').update(pass).digest('base64')}\n`;
  fs.writeFileSync(htpasswdPath, entry, 'utf8');
  const guard = [
    '',
    `# >>> ${GUARD_SENTINEL} (generated by build-epik.cjs --staging) — MUST NOT reach production >>>`,
    '# Primary: HTTP Basic Auth. If this ever leaks to prod the site 401s (loud), not de-indexes (silent).',
    'AuthType Basic',
    'AuthName "prb-staging"',
    `AuthUserFile ${stagingRoot}/.htpasswd`,
    'Require valid-user',
    '# Secondary: noindex header (belt-and-suspenders; Basic Auth already blocks crawlers).',
    'Header always set X-Robots-Tag "noindex, nofollow"',
    '<Files ".htpasswd">',
    '  Require all denied',
    '</Files>',
    `# <<< ${GUARD_SENTINEL} <<<`,
    '',
  ].join('\n');
  fs.appendFileSync(htaccessPath, guard, 'utf8');
  guardNote = `  ✓ STAGING guard appended (Basic Auth user "${user}" + noindex), .htpasswd written`;
} else {
  // Production: assert the artifact is guard-free, and scrub any staging leftover.
  const ht = fs.readFileSync(htaccessPath, 'utf8');
  const hits = [];
  if (ht.includes(GUARD_SENTINEL)) hits.push('staging sentinel');
  if (/^\s*(AuthType|AuthName|AuthUserFile|Require\s+valid-user)\b/mi.test(ht)) hits.push('Basic Auth directive');
  if (/Header\b.*X-Robots-Tag.*noindex/i.test(ht)) hits.push('blanket noindex header');
  if (hits.length) {
    console.error(`  ✗ production .htaccess contains a staging guard (${hits.join(', ')}) — refusing to build a production artifact`);
    process.exit(1);
  }
  if (fs.existsSync(htpasswdPath)) fs.unlinkSync(htpasswdPath); // scrub stale staging .htpasswd
  guardNote = '  ✓ production artifact verified guard-free (no Basic Auth, no blanket noindex)';
}

console.log('  Epik artifacts written to dist/:');
console.log(`  ✓ resolver-config.php  (PRODUCT_RE = /${productPattern}/)`);
console.log(`  ✓ redirects.php        (${redirectCount} 301 entr${redirectCount === 1 ? 'y' : 'ies'})`);
console.log(`  ✓ gone.html            (${goneHtml.length} bytes, noindex verified)`);
console.log('  ✓ .htaccess');
console.log('  ✓ resolver.php');
console.log('  ✓ _env.php             (dir_resolved + opcache reporter)');
console.log(guardNote);
