// =============================================================================
//  build-epik.cjs
//  Copyright © 2026 TieredUp Tech, Inc.
//
//  Generates the static-hosting artifacts the Epik/Apache stack needs, INTO dist/,
//  so they survive `vite build` emptying dist/. Run after prerender.cjs.
//
//  Emits into dist/:
//    - resolver-config.php  : PRODUCT_RE copied verbatim out of server.cjs
//                             (single source of truth for the product boundary)
//    - redirects.php        : the 301 map, from product-redirects.json
//    - gone.html            : the 410 shell, transformed from index.html exactly
//                             the way server.cjs builds GONE_SHELL at boot
//    - .htaccess            : copied from deploy/.htaccess
//    - resolver.php         : copied from deploy/resolver.php
// =============================================================================

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');
const DEPLOY = path.join(ROOT, 'deploy');

if (!fs.existsSync(DIST)) {
  console.error(`  ✗ dist/ not found at ${DIST} — run the vite build + prerender first`);
  process.exit(1);
}

// ── 1. Extract PRODUCT_RE from server.cjs (copy, never retype) ───────────────
const serverSrc = fs.readFileSync(path.join(ROOT, 'server.cjs'), 'utf8');
const m = serverSrc.match(/const PRODUCT_RE = \/(.+)\/;\s*$/m);
if (!m) {
  console.error('  ✗ could not locate `const PRODUCT_RE = /.../;` in server.cjs');
  process.exit(1);
}
const productPattern = m[1]; // e.g. ^\/parts\/[^/]+\/[^/]+-\d+\/?$
if (productPattern.includes('#') || productPattern.includes("'")) {
  // Our PHP wrapper uses `#` as the delimiter inside a single-quoted string.
  console.error('  ✗ PRODUCT_RE contains a `#` or a single quote — adjust the PHP delimiter/escaping');
  process.exit(1);
}
const resolverConfig =
  '<?php\n' +
  '// GENERATED by build-epik.cjs — DO NOT EDIT.\n' +
  '// PRODUCT_RE copied verbatim from server.cjs so the product/non-product boundary\n' +
  '// is byte-identical to the Node stack. `#` delimiter avoids escaping the slashes.\n' +
  "define('RESOLVER_PRODUCT_RE', '#" + productPattern + "#');\n";
fs.writeFileSync(path.join(DIST, 'resolver-config.php'), resolverConfig, 'utf8');

// ── 2. redirects.php from product-redirects.json (drop "//" comment keys) ────
let rawMap = {};
try {
  rawMap = JSON.parse(fs.readFileSync(path.join(ROOT, 'product-redirects.json'), 'utf8'));
} catch (e) {
  console.warn(`  ⚠ product-redirects.json not read (${e.message}) — emitting empty map (all 410)`);
}
const phpStr = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
let redirectCount = 0;
let redirectsPhp = '<?php\n// GENERATED by build-epik.cjs from product-redirects.json — DO NOT EDIT.\nreturn array(\n';
for (const [k, v] of Object.entries(rawMap)) {
  if (k.startsWith('//')) continue; // JSON comment convention
  redirectsPhp += '  ' + phpStr(k) + ' => ' + phpStr(v) + ',\n';
  redirectCount++;
}
redirectsPhp += ');\n';
fs.writeFileSync(path.join(DIST, 'redirects.php'), redirectsPhp, 'utf8');

// ── 3. gone.html — same transform server.cjs applies to build GONE_SHELL ─────
let goneHtml;
try {
  goneHtml = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8')
    .replace(/\s*<meta name="(?:robots|googlebot|bingbot)"[^>]*>/gi, '')
    .replace(/\s*<link[^>]*rel="canonical"[^>]*>/gi, '')
    .replace(/<head>/i, '<head>\n    <meta name="robots" content="noindex">');
} catch (e) {
  goneHtml = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
    + '<meta name="robots" content="noindex">'
    + '<title>Product Not Found — Pro Rig Builder</title></head>'
    + '<body><h1>Product Not Found</h1></body></html>';
}
// Guard: a 410 shell must never advertise itself as indexable.
if (/content="index/i.test(goneHtml) || !/content="noindex"/i.test(goneHtml)) {
  console.error('  ✗ gone.html failed the noindex invariant — index directive present or noindex missing');
  process.exit(1);
}
fs.writeFileSync(path.join(DIST, 'gone.html'), goneHtml, 'utf8');

// ── 4. Copy the static config into dist/ (edit these in deploy/, never in dist/)
fs.copyFileSync(path.join(DEPLOY, '.htaccess'), path.join(DIST, '.htaccess'));
fs.copyFileSync(path.join(DEPLOY, 'resolver.php'), path.join(DIST, 'resolver.php'));

console.log('  Epik artifacts written to dist/:');
console.log(`  ✓ resolver-config.php  (PRODUCT_RE = /${productPattern}/)`);
console.log(`  ✓ redirects.php        (${redirectCount} 301 entr${redirectCount === 1 ? 'y' : 'ies'})`);
console.log(`  ✓ gone.html            (${goneHtml.length} bytes, noindex verified)`);
console.log('  ✓ .htaccess');
console.log('  ✓ resolver.php');
