// =============================================================================
//  build-epik.cjs
//  Copyright © 2026 TieredUp Tech, Inc.
//
//  Generates the static-hosting artifacts the Epik/Apache stack needs, INTO dist/,
//  so they survive `vite build` emptying dist/. Run after prerender.cjs.
//
//  Emits into dist/:
//    - resolver-config.php  : PRODUCT_RE copied verbatim out of server.cjs
//                             (single source of truth for the product boundary)
//    - redirects.php        : the 301 map, from product-redirects.json
//    - gone.html            : the 410 shell, transformed from index.html exactly
//                             the way server.cjs builds GONE_SHELL at boot
//    - .htaccess            : copied from deploy/.htaccess
//    - resolver.php         : copied from deploy/resolver.php
// =============================================================================

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');
const DEPLOY = path.join(ROOT, 'deploy');

// Staging builds get a Basic-Auth + noindex guard appended to .htaccess. It is
// NEVER part of a production artifact — see the STAGING branch vs the production
// self-check at the end of this script. The sentinel is what the production
// deploy greps for to refuse shipping a contaminated .htaccess.
const STAGING = process.argv.includes('--staging');
const GUARD_SENTINEL = 'PRB-STAGING-GUARD';

// ── APR1 (Apache MD5-crypt) htpasswd hashing ────────────────────────────────
// MEASURED 2026-08-12 on the Epik box: LiteSpeed does NOT accept {SHA} htpasswd
// entries. It does not warn, does not log a format error — it just answers 401
// on every request, exactly as if the password were wrong. The credential can be
// byte-perfect and the modes correct and staging still 401s forever, which sends
// you chasing permissions instead of the format. openssl proved it on the box:
//     {SHA}1Owkl1srtSqntLaMo66IZP+by3c=  -> 401
//     openssl passwd -apr1 <same password> -> 200
// APR1 is what LiteSpeed and Apache 2.4 both accept, so it is the only format
// this repo generates. The shell scripts (deploy/install-phase-a.sh,
// scripts/rotate-staging-auth.sh) use `openssl passwd -apr1` — there is no
// htpasswd binary on that host. Here it is implemented directly rather than
// shelling out, so a `node build-epik.cjs --staging` on a dev box with no
// openssl on PATH still produces a byte-identical entry. Verified against
// `openssl passwd -apr1 -salt <s>` over 67 cases including the pl-=16 loop
// boundaries (15/16/17-char passwords) and 1/4/8-char salts.
const APR1_ITOA64 = './0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
function md5(...bufs) {
  const h = crypto.createHash('md5');
  for (const b of bufs) h.update(b);
  return h.digest();
}
function apr1(password, salt) {
  const pw = Buffer.from(password, 'utf8');
  const sa = Buffer.from(salt, 'utf8');

  let final = md5(pw, sa, pw);
  const ctx = [pw, Buffer.from('$apr1$', 'utf8'), sa];
  for (let pl = pw.length; pl > 0; pl -= 16) ctx.push(final.subarray(0, Math.min(pl, 16)));
  for (let i = pw.length; i; i >>= 1) ctx.push(i & 1 ? Buffer.from([0]) : pw.subarray(0, 1));
  final = md5(...ctx);

  // 1000 stretching rounds — the part that makes APR1 worth having over {SHA}.
  for (let i = 0; i < 1000; i++) {
    const c = [i & 1 ? pw : final];
    if (i % 3) c.push(sa);
    if (i % 7) c.push(pw);
    c.push(i & 1 ? final : pw);
    final = md5(...c);
  }

  let out = '';
  const enc = (b0, b1, b2, n) => {
    let v = (b0 << 16) | (b1 << 8) | b2;
    for (let i = 0; i < n; i++) { out += APR1_ITOA64[v & 0x3f]; v >>= 6; }
  };
  enc(final[0], final[6], final[12], 4);
  enc(final[1], final[7], final[13], 4);
  enc(final[2], final[8], final[14], 4);
  enc(final[3], final[9], final[15], 4);
  enc(final[4], final[10], final[5], 4);
  enc(0, 0, final[11], 2);
  return `$apr1$${salt}$${out}`;
}
const apr1Salt = () =>
  Array.from(crypto.randomBytes(8), (b) => APR1_ITOA64[b & 0x3f]).join('');

if (!fs.existsSync(DIST)) {
  console.error(`  ✗ dist/ not found at ${DIST} — run the vite build + prerender first`);
  process.exit(1);
}

// ── 1. Extract PRODUCT_RE from server.cjs (copy, never retype) ───────────────
const serverSrc = fs.readFileSync(path.join(ROOT, 'server.cjs'), 'utf8');
const m = serverSrc.match(/const PRODUCT_RE = \/(.+)\/;\s*$/m);
if (!m) {
  console.error('  ✗ could not locate `const PRODUCT_RE = /.../;` in server.cjs');
  process.exit(1);
}
const productPattern = m[1]; // e.g. ^\/parts\/[^/]+\/[^/]+-\d+\/?$
if (productPattern.includes('#') || productPattern.includes("'")) {
  // Our PHP wrapper uses `#` as the delimiter inside a single-quoted string.
  console.error('  ✗ PRODUCT_RE contains a `#` or a single quote — adjust the PHP delimiter/escaping');
  process.exit(1);
}
const resolverConfig =
  '<?php\n' +
  '// GENERATED by build-epik.cjs — DO NOT EDIT.\n' +
  '// PRODUCT_RE copied verbatim from server.cjs so the product/non-product boundary\n' +
  '// is byte-identical to the Node stack. `#` delimiter avoids escaping the slashes.\n' +
  "define('RESOLVER_PRODUCT_RE', '#" + productPattern + "#');\n";
fs.writeFileSync(path.join(DIST, 'resolver-config.php'), resolverConfig, 'utf8');

// ── 2. redirects.php from product-redirects.json (drop "//" comment keys) ────
let rawMap = {};
try {
  rawMap = JSON.parse(fs.readFileSync(path.join(ROOT, 'product-redirects.json'), 'utf8'));
} catch (e) {
  console.warn(`  ⚠ product-redirects.json not read (${e.message}) — emitting empty map (all 410)`);
}
const phpStr = (s) => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
let redirectCount = 0;
let redirectsPhp = '<?php\n// GENERATED by build-epik.cjs from product-redirects.json — DO NOT EDIT.\nreturn array(\n';
for (const [k, v] of Object.entries(rawMap)) {
  if (k.startsWith('//')) continue; // JSON comment convention
  redirectsPhp += '  ' + phpStr(k) + ' => ' + phpStr(v) + ',\n';
  redirectCount++;
}
redirectsPhp += ');\n';
fs.writeFileSync(path.join(DIST, 'redirects.php'), redirectsPhp, 'utf8');

// ── 3. gone.html — same transform server.cjs applies to build GONE_SHELL ─────
let goneHtml;
try {
  goneHtml = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8')
    .replace(/\s*<meta name="(?:robots|googlebot|bingbot)"[^>]*>/gi, '')
    .replace(/\s*<link[^>]*rel="canonical"[^>]*>/gi, '')
    .replace(/<head>/i, '<head>\n    <meta name="robots" content="noindex">');
} catch (e) {
  goneHtml = '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">'
    + '<meta name="robots" content="noindex">'
    + '<title>Product Not Found — Pro Rig Builder</title></head>'
    + '<body><h1>Product Not Found</h1></body></html>';
}
// Guard: a 410 shell must never advertise itself as indexable.
if (/content="index/i.test(goneHtml) || !/content="noindex"/i.test(goneHtml)) {
  console.error('  ✗ gone.html failed the noindex invariant — index directive present or noindex missing');
  process.exit(1);
}
fs.writeFileSync(path.join(DIST, 'gone.html'), goneHtml, 'utf8');

// ── 4. Copy the static config into dist/ (edit these in deploy/, never in dist/)
fs.copyFileSync(path.join(DEPLOY, '.htaccess'), path.join(DIST, '.htaccess'));
fs.copyFileSync(path.join(DEPLOY, 'resolver.php'), path.join(DIST, 'resolver.php'));
// _env.php reports the R1 invariant + opcache state per worker. It ships in
// every artifact (both stacks) so the pull healthcheck and the watchdog can
// assert on it — see DESIGN-pull-deploy.md §3.3 / §6.9.
fs.copyFileSync(path.join(DEPLOY, '_env.php'), path.join(DIST, '_env.php'));

// ── 5. Staging guard (Basic Auth primary, noindex secondary) OR production
//      self-check that no guard is present. Basic Auth is deliberately the
//      primary layer: if it ever leaks to prod the site 401s and is noticed in
//      minutes, whereas a stray noindex de-indexes silently (the 2026-07-27
//      incident). The guard is generated ONLY here, only under --staging.
const htaccessPath = path.join(DIST, '.htaccess');
const htpasswdPath = path.join(DIST, '.htpasswd');
let guardNote = '';
if (STAGING) {
  const authRaw = process.env.EPIK_STAGING_BASIC_AUTH || '';
  if (!authRaw.includes(':')) {
    console.error('  ✗ --staging requires EPIK_STAGING_BASIC_AUTH="user:password"');
    process.exit(2);
  }
  const stagingRoot = (process.env.EPIK_REMOTE_ROOT || '').replace(/\/+$/, '');
  if (!stagingRoot) {
    console.error('  ✗ --staging requires EPIK_REMOTE_ROOT (the staging docroot) for the AuthUserFile path');
    process.exit(2);
  }
  const ci = authRaw.indexOf(':');
  const user = authRaw.slice(0, ci);
  const pass = authRaw.slice(ci + 1);
  // APR1 htpasswd entry. NOT {SHA}: LiteSpeed silently 401s on {SHA} — see the
  // apr1() comment at the top of this file before changing this line.
  const entry = `${user}:${apr1(pass, apr1Salt())}\n`;
  fs.writeFileSync(htpasswdPath, entry, 'utf8');
  const guard = [
    '',
    `# >>> ${GUARD_SENTINEL} (generated by build-epik.cjs --staging) — MUST NOT reach production >>>`,
    '# Primary: HTTP Basic Auth. If this ever leaks to prod the site 401s (loud), not de-indexes (silent).',
    'AuthType Basic',
    'AuthName "prb-staging"',
    `AuthUserFile ${stagingRoot}/.htpasswd`,
    'Require valid-user',
    '# Secondary: noindex header (belt-and-suspenders; Basic Auth already blocks crawlers).',
    'Header always set X-Robots-Tag "noindex, nofollow"',
    '<Files ".htpasswd">',
    '  Require all denied',
    '</Files>',
    `# <<< ${GUARD_SENTINEL} <<<`,
    '',
  ].join('\n');
  fs.appendFileSync(htaccessPath, guard, 'utf8');
  guardNote = `  ✓ STAGING guard appended (Basic Auth user "${user}" + noindex), .htpasswd written`;
} else {
  // Production: assert the artifact is guard-free, and scrub any staging leftover.
  const ht = fs.readFileSync(htaccessPath, 'utf8');
  const hits = [];
  if (ht.includes(GUARD_SENTINEL)) hits.push('staging sentinel');
  if (/^\s*(AuthType|AuthName|AuthUserFile|Require\s+valid-user)\b/mi.test(ht)) hits.push('Basic Auth directive');
  if (/Header\b.*X-Robots-Tag.*noindex/i.test(ht)) hits.push('blanket noindex header');
  if (hits.length) {
    console.error(`  ✗ production .htaccess contains a staging guard (${hits.join(', ')}) — refusing to build a production artifact`);
    process.exit(1);
  }
  if (fs.existsSync(htpasswdPath)) fs.unlinkSync(htpasswdPath); // scrub stale staging .htpasswd
  guardNote = '  ✓ production artifact verified guard-free (no Basic Auth, no blanket noindex)';
}

console.log('  Epik artifacts written to dist/:');
console.log(`  ✓ resolver-config.php  (PRODUCT_RE = /${productPattern}/)`);
console.log(`  ✓ redirects.php        (${redirectCount} 301 entr${redirectCount === 1 ? 'y' : 'ies'})`);
console.log(`  ✓ gone.html            (${goneHtml.length} bytes, noindex verified)`);
console.log('  ✓ .htaccess');
console.log('  ✓ resolver.php');
console.log('  ✓ _env.php             (dir_resolved + opcache reporter)');
console.log(guardNote);
