<?php
// GENERATED by build-epik.cjs from product-redirects.json — DO NOT EDIT.
return array(
  '/parts/ram/corsair-vengeance-ddr5-32gb-2x16gb-5600mhz-cl36-40001' => '/parts/ram/corsair-vengeance-32gb-2-x-16gb-ddr5-5600-pc5-44800-desktop-memory-model-cmk32gx-102343',
  '/parts/ram/corsair-vengeance-ddr5-64gb-2x32gb-5600mhz-cl40-40003' => '/parts/ram/corsair-vengeance-64gb-2-x-32gb-288pin-pc-ram-ddr5-5600-pc5-44800-desktop-memory-102131',
  '/parts/ram/gskill-trident-z5-rgb-ddr5-32gb-2x16gb-6400mhz-cl32-40006' => '/parts/ram/g-skill-trident-z5-rgb-series-32gb-2-x-16gb-288pin-pc-ram-ddr5-6400-pc5-51200-de-102207',
  '/parts/ram/gskill-trident-z5-neo-ddr5-32gb-2x16gb-6000mhz-cl30-40007' => '/parts/ram/g-skill-trident-z5-neo-series-amd-expo-32gb-2-x-16gb-288pin-pc-ram-ddr5-6000-pc5-102225',
  '/parts/ram/gskill-trident-z5-rgb-ddr5-64gb-2x32gb-6000mhz-cl30-40008' => '/parts/ram/g-skill-trident-z5-rgb-series-64gb-2-x-32gb-288pin-pc-ram-ddr5-6000-pc5-48000-de-102219',
  '/parts/ram/gskill-ripjaws-s5-ddr5-32gb-2x16gb-5600mhz-cl28-40010' => '/parts/ram/g-skill-ripjaws-s5-series-32gb-2-x-16gb-ddr5-5600-desktop-memory-model-f55600j36-102196',
  '/parts/ram/corsair-vengeance-lpx-ddr4-16gb-2x8gb-3200mhz-cl16-40027' => '/parts/ram/corsair-vengeance-lpx-16gb-2-x-8gb-288pin-pc-ram-ddr4-3200-pc4-25600-desktop-mem-102117',
  '/parts/ram/gskill-ripjaws-v-ddr4-32gb-2x16gb-3600mhz-cl18-40028' => '/parts/ram/g-skill-ripjaws-v-series-32gb-2-x-16gb-288pin-pc-ram-ddr4-3600-pc4-28800-desktop-102111',
  '/parts/ram/gskill-ripjaws-v-ddr4-16gb-2x8gb-3200mhz-cl16-40029' => '/parts/ram/g-skill-ripjaws-v-series-16gb-2-x-8gb-288pin-pc-ram-ddr4-3200-pc4-25600-desktop-102101',
  '/parts/ram/gskill-trident-z-rgb-ddr4-32gb-2x16gb-3600mhz-cl16-40030' => '/parts/ram/gskill-ddr4-32gb-pc-3600-cl18-kit-2x16gb-32gtzr-trirgb-100512',
  '/parts/ram/kingston-fury-beast-ddr4-32gb-2x16gb-3200mhz-cl16-40031' => '/parts/ram/kingston-fury-beast-32gb-2-x-16gb-288pin-pc-ram-ddr4-3200-pc4-25600-memory-deskt-101957',
  '/parts/ram/kingston-fury-beast-ddr4-16gb-2x8gb-3200mhz-cl16-40032' => '/parts/ram/kingston-fury-beast-16gb-2-x-8gb-288pin-pc-ram-ddr4-3200-pc4-25600-desktop-memor-102153',
);
