<?php
// GENERATED by build-epik.cjs — DO NOT EDIT.
// PRODUCT_RE copied verbatim from server.cjs so the product/non-product boundary
// is byte-identical to the Node stack. `#` delimiter avoids escaping the slashes.
define('RESOLVER_PRODUCT_RE', '#^\/parts\/[^/]+\/[^/]+-\d+\/?$#');
